### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by rogard** [albfan/dwww#1]
I would like to know what steps I could take to diagnose this problem.

**Comment by albfan** [comment]
Try to google a bit:

https://www.1and1.com/cloud-community/learn/web-server/server-management/how-to-fix-http-error-code-500-internal-server-error/

If it is related to dwww, update here and I can take a look

**Comment by rogard** [comment]
Wouldn't "Failed to flush CGI output to client, referer: http://yogurt/dwww/menu/" denote a problem with dwww? https://stackoverflow.com/questions/49846597/internal-server-error-port-80

**Comment by albfan** [comment]
You should upload a log about that error.

That denote a problem with CGI, but CGI could be code, server or app

**Comment by rogard** [comment]
Thanks. The log, conf, and tests to discriminate between possible causes of the error are at the link I sent.

**Comment by albfan** [comment]
That's not a reproducible use case. You need to provide:

- environment (distro version, apache version)
- steps you take to install 
- reproducible steps that lead you to an error, you can upload a screencast if you want.

redundancy is preferred. Do not open an issue and point to data in an external URL. The issue needs to provide all required info.

Avoid non-essential info. Provide a conf file with its comments only adds noise.

Take this project as example https://github.com/primefaces/primefaces/issues/new See all info required to not close directly the issue.
